### ISSUE TITLE
from utils import torch_msssim, dail: ImportError cannot import name 'dali'

### ISSUE THREAD

**Issue by Jillian2017** [tongxyh/ImageCompression_VariableRate#1]
Hi:
It's very kind of you to release source code of your interesting work.
I'm trying to run the train.py, but came across this error.
In the directory of utils, there are ops.py and torch_msssim.py, the dali.py is not found. 
Hope your reply.
Best regards.

Jillian

**Comment by tongxyh** [comment]
Hi, 
I have just updated the train.py. now It uses only the default Pytorch Dataloder.
Please check wheter it works correctly now.
Best,

Tong

**Comment by Jillian2017** [comment]
Yeah, it's okay of reading data.
Anohter issue is as below:
   _File "train.py", line 75, in <module>
       image_comp = model.Image_Coder_context(M=M. N2=N2).cuda()
  File "/xx/modules/model.py", line 193, in __init__
      self.guassian_entropy_func = Distribution_for_entropy()
NameError: name 'Distribution_for_entropy' is not defined.__

I find there is Distribution_for_entropy2 in gaussian_entropy_model.py. Is there any difference?
Hope your reply.

Jillian

**Comment by tongxyh** [comment]
Hi, bug fixed, 
BTW, If you are going to train your own Scaler(scaler.pkl), please download pretrained AE models(ae.pkl) first and set LOAD_EXIST=True in `train.py` before starting your training.

Tong
